hyperskill_project:
  id: 90
  ide_files: https://cogniterra.org/media/attachments/lesson/24581/additional_files.json
  is_template_based: false
  use_ide: true
  environment: unittest
update_date: "Thu, 25 Apr 2024 16:20:44 UTC"
stages:
  - id: 500
    step: 8002
    is_completed: false
  - id: 501
    step: 8003
    is_completed: false
  - id: 502
    step: 8004
    is_completed: false
  - id: 503
    step: 8005
    is_completed: false
topics:
  0:
    - title: Introduction to Python
      theory_id: 5204
    - title: Writing first program
      theory_id: 5208
    - title: Multi-line programs
      theory_id: 5233
    - title: Naming variables
      theory_id: 5885
    - title: Basic data types
      theory_id: 5852
    - title: Variables
      theory_id: 5859
  1:
    - title: Taking user's input
      theory_id: 5913
    - title: Program with numbers
      theory_id: 5872
    - title: If statement
      theory_id: 5953
    - title: Else statement
      theory_id: 5932
    - title: Importing modules
      theory_id: 6019
    - title: Elif statement
      theory_id: 5926
    - title: Math functions
      theory_id: 6256
    - title: Integer arithmetic
      theory_id: 5865
    - title: Invoking functions
      theory_id: 5891
    - title: Boolean type and operations. True and false
      theory_id: 6025
    - title: Comparisons
      theory_id: 5920
    - title: Quotes and multi-line strings
      theory_id: 5814
  2:
    - title: PyCharm basics
      theory_id: 6193
    - title: Running Python applications in PyCharm
      theory_id: 19153
    - title: Command line arguments
      theory_id: 7981
    - title: Argparse module
      theory_id: 11389
    - title: List
      theory_id: 5979
    - title: Indexes
      theory_id: 6189
    - title: String formatting
      theory_id: 6037
    - title: Type casting
      theory_id: 6224
  3:
    - title: For loop
      theory_id: 6065
    - title: While loop
      theory_id: 5940
    - title: Debugging Python applications in PyCharm
      theory_id: 19163
    - title: Program execution
      theory_id: 6047
    - title: Errors
      theory_id: 6052
    - title: Declaring functions
      theory_id: 5900
